name: Lesson 1

on:
  push:
    branches:
      - lesson-1
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest django_mock_queries six coverage
      - name: Unit Tests
        run: |
          coverage run -m --source=./hangry_api pytest
          coverage report
  deploy:
    needs: [build_and_test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v2
      - name: Disable Debug
        run: |
          sed -i 's/DEBUG = True/DEBUG = False/g' hangry_api/hangry_api/settings.py
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      - name: '**PLACEHOLDER** Deploy to Elastic Beanstalk'
        run: echo Placeholder for Deployment
